security:
#    role_hierarchy:
#        ROLE_PATIENT: [ ROLE_PATIENT ]
#        ROLE_CLINIC_WORKER: [ ROLE_CLINIC_WORKER ]
#        ROLE_DOCTOR: [ ROLE_PATIENT, ROLE_CLINIC_WORKER, ROLE_DOCTOR ]
#        ROLE_ADMIN: [ ROLE_PATIENT, ROLE_CLINIC_WORKER, ROLE_DOCTOR, ROLE_ADMIN ]
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: "login_form[email]"
                password_parameter: "login_form[password]"
            logout:
                path: logout
                target: login

    access_control:
       - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
